# Generated by Django 4.0.5 on 2022-06-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('price_dollar', models.FloatField()),
                ('supply_date', models.DateField()),
                ('price_ruble', models.FloatField()),
            ],
        ),
    ]
